### ISSUE TITLE
Text field background color is not updated

### ISSUE THREAD

**Issue by marlycormar** [ctsit/complex_field_validation#2]
# Correcting bug in the given hook
The given hook has a small bug. A fix should be included in the module. Please see below for more information.

## Expected behavior of the hook
If the user enters a valid input after an invalid input, the text box field background-color should change from red to white (indicating the value is now correct).

## Current behavior of the hook
If the user enters a valid input after an invalid input, where the valid input is taken from those values additionally added to the **Field Note**, the text box field background-color will not be updated, i.e., the background color of the field will still be red.

## ToDo
Include bug fix into the module.

**Comment by tbembersimeao** [comment]
A fix for that (fa21d75) is already included on release 1.1.0. Closing this issue.
